---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.deployment.name | quote }}
  labels:
    app: {{ .Values.deployment.name | quote }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name | quote }}
  strategy:
    type: RollingUpdate      
  template:
    metadata:
      name: {{ .Values.deployment.name | quote }}
      labels:
        app: {{ .Values.deployment.name | quote }}
    spec:
      volumes:
        - name: github-ssh
          secret:
            defaultMode: 420
            secretName: github-ssh
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Values.deployment.name | quote }}
          image: {{ .Values.deployment.image | quote }}
          env:
            - name: TZ
              value: {{ .Values.deployment.environment.timezone | quote }}
          ports:
            - containerPort: {{ .Values.deployment.serverPort }}
              name: server-port
            - containerPort: {{ .Values.deployment.managementPort }}
              name: management-port
          volumeMounts:
            - mountPath: /root/.ssh
              name: github-ssh
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.deployment.managementEndpoint }}
              port: {{ .Values.deployment.managementPort }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: {{ .Values.deployment.managementEndpoint }}
              port: {{ .Values.deployment.managementPort }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
